name: Auto Run Training and Streamlit

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy mỗi 6 giờ đúng phút 00 (UTC)
  workflow_dispatch:       # Cho phép chạy thủ công nếu cần

jobs:
  run-training-streamlit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Cho phép commit & push thay đổi

    steps:
      # Bước 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Bước 2: Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Không cần playwright nếu không sử dụng, bỏ nếu không cần

      # Bước 4: Chạy script huấn luyện (huanluyen6.py)
      - name: Run training script
        run: |
          python huanluyen6.py
        timeout-minutes: 15  # Tăng thời gian timeout nếu huấn luyện lâu

      # Bước 5: Chạy script Streamlit (streamlit6.py)
      - name: Run Streamlit script
        run: |
          streamlit run streamlit6.py --server.port 8501 &
          sleep 10  # Đợi ứng dụng khởi động (có thể điều chỉnh thời gian)
        timeout-minutes: 5

      # Bước 6: Kiểm tra và commit nếu có thay đổi (mô hình hoặc dữ liệu)
      - name: Commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          if git status --porcelain | grep -E "models/|all_cities_aqi_data.csv"; then
            echo "📦 File mô hình hoặc dữ liệu thay đổi, tiến hành commit..."
            git add models/* all_cities_aqi_data.csv
            git commit -m "🔄 Auto update models and data"
            git push
          else
            echo "✅ Không có thay đổi nào trong mô hình hoặc dữ liệu."
